#!/bin/sh
PATH=${PATH}:/sbin:/usr/bin:/bin

##
# Flush any existing rules and set default policies
iptables -F
iptables -P INPUT   ACCEPT
iptables -P OUTPUT  ACCEPT
iptables -P FORWARD ACCEPT
iptables -t nat -F

##
# block persistent script kiddies
iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --set
iptables -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 3 -j DROP

##
# allow certain ports
iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -j ACCEPT

##
# accept related replies
iptables -A INPUT -i eth0 -m state --state RELATED -j ACCEPT

##
# block connection attempts to any port if not explicitly allowed above
iptables -A INPUT -i eth0 -p tcp --dport 0:1024 --jump DROP
iptables -A INPUT -i eth0 -p udp --dport 0:1024 --jump DROP
