#!/usr/bin/env bash

basedir=$(cd $(dirname $0)/../..; pwd)
source $basedir/includes
source $basedir/main.conf
packages=$(cat $basedir/etc/packages.$distro)

# must be root
if [[ ! $youare = "root" ]]; then
  echo "you must become root to run this"
  exit 0
fi

getready "set editing mode and password for root"
echo "set editing-mode vi" > ~/.inputrc
passwd

getready "upgrade packages"
apt-get update
apt-get upgrade

getready "install key packages"
apt-get install $(echo $packages)

getready "install and start firewall"
cp -p $basedir/files/server/firewall_rules /usr/local/bin
/usr/local/bin/firewall_rules
iptables -L

getready "create users"

# primary user
useradd -g $group -m -s $default_shell -c "$primary_comment" $primary_user
echo "set password for $primary_user"
passwd $primary_user
chown -R $primary_user:$group $basedir/files/user/
su $primary_user -c "$basedir/files/user/run"

# optional additional users
ask_again=1
while [[ $ask_again ]]; do
  read -s -n 1 -p "create another user in group \"$group\"? [y|N] " moreusers

  if [[ $moreusers = 'y' ]] || [[ $moreusers = 'Y' ]]; then
    read -s -p "enter username: " user
    read -s -p "enter name (comment) for $user " friendlyname

    if [[ -d /home/$user ]]; then
      echo "user $user already exists"
    else
      useradd -g $group -m -s $default_shell -c "$friendlyname" $user
      echo "set password for $user"
      passwd $user
    fi

  else
    ask_again=0
  fi
done

# directories under /opt owned by primary user
getready "prep /opt"
for optdir in $optdirs; do
  DIR=/opt/$optdir
  echo "making $DIR"
  mkdir -p $DIR
  chown $primary_user:$group $DIR
done

# manual steps
echo "Do the following to complete basic setup:"
echo "  vim /etc/ssh/sshd_config   # remove root login and allow PK auth only"
echo "  /etc/init.d/ssh restart"
echo "  vim /etc/rc.local          # to invoke /usr/local/bin/firewall_rules upon reboot"
