#!/usr/bin/env bash

youare=$(whoami)

getready() {
  echo $1
  read -s -n 1 -p "press q to quit, any other key to continue " cmd
  echo ""
  if [[ $cmd = 'q' ]] || [[ $cmd = 'Q' ]]; then
    exit 0
  fi
}

update_authorized_keys() {
  FIL=$HOME/.ssh/authorized_keys
  [[ -f $FIL ]] || ( touch $FIL && chmod 600 $FIL )
  vim $FIL
}

install_user_files() {
  fromdir=$1

  # shared files per user.conf
  if [[ -f $fromdir/user.conf ]]; then
    source $fromdir/user.conf

    for sharedfile in $INSTALL_SHARES; do
      fromfile=$basedir/files/shared/$sharedfile

      if [[ -f $fromfile ]]; then
        echo "installing shared file $sharedfile"
        tofile=/home/$USERNAME/$sharedfile
        mkdir -p $(dirname $tofile)
        cp $fromfile $tofile
        chown $USERNAME:$GROUP $tofile
      else
        echo "skipping missing shared file $shared_file"
      fi

    done
  fi

  # user-specific files
  for subdir in bin etc; do
    if [[ -d $fromdir/$subdir ]]; then
      for nextfile in $(ls $fromdir/$subdir); do

        if [[ -f $HOME/$subdir/$nextfile ]]; then
          echo "$subdir/$nextfile is already installed"
        else
          echo "installing $subdir/$nextfile"
          mkdir -p $HOME/$subdir
          cp $fromdir/$subdir/$nextfile $HOME/$subdir
        fi

      done
    fi
  done

  if [[ -f $HOME/etc/pyenv.helpers ]]; then
    source $HOME/etc/pyenv.helpers
    echo "creating Python virtual environment directory $VIRTUALENV_BASEDIR"
    mkdir -p $VIRTUALENV_BASEDIR
  fi
}

discover_os() {
  distro=""
  supported=$(ls $basedir/etc/packages.* | cut -f2 -d'.')

  for attempt in $supported; do
    hit=$(uname -v | grep -i $attempt)
    if [[ -n $hit ]]; then 
      distro=$attempt
    fi
  done

  if [[ -n $distro ]]; then
    echo $distro
  else
    echo "unsupported distro: $(uname -v)"
  fi
}
  
distro=$(discover_os)
