#!/usr/bin/env bash

basedir=$(cd $(dirname $0)/../../..; pwd)
workdir=$(cd $(dirname $0); pwd)
source $basedir/etc/includes

getready "set editing mode"
echo "set editing-mode vi" > $HOME/.inputrc

getready "build local OpenSSH keys"
ssh-keygen -t rsa

getready "paste and save an OpenSSH public key for remote access"
FIL=$HOME/.ssh/authorized_keys
touch $FIL
chmod 600 $FIL
vim $FIL

getready "install helper files for $youare"
install_user_files $workdir

getready "setup dotfiles"
mkdir -p $HOME/git
cd $HOME/git
git clone https://github.com/peterjpierce/dotfiles.git
cd $HOME
for FIL in gitconfig vimrc tmux.conf; do
  ln -s git/dotfiles/$FIL .${FIL}
  ls -l .${FIL}
done

getready "setup vim and its plugins"
$workdir/vimsetup

# manual steps
echo "Do the following to complete basic setup for user \"$youare\":"
echo "  - download, build and install python 2 and 3 to /opt/python using $HOME/bin/pybuild"
echo "  - edit .bashrc or .profile to set PATH for Python, and to source $HOME/etc/pyenv.helpers"
echo "  - verify PK auth working from remote accounts"
echo "  - update $HOME/.ssh/config within remote accounts"
