#!/usr/bin/env bash

basedir=$(cd $(dirname $0)/../..; pwd)

# user prompts
getready() {
  echo $1
  read -s -n 1 -p "press q to quit, any other key to continue " cmd
  echo ""
  if [[ $cmd = 'q' ]] || [[ $cmd = 'Q' ]]; then
    exit 0
  fi
}

getready "set editing mode and add keys"
read -p "press enter to continue..."
set -o vi
echo "set editing-mode vi" > $HOME/.inputrc
ssh-keygen -t rsa

getready "paste and save an OpenSSH public key for this user's access"
FIL=$HOME/.ssh/authorized_keys
touch $FIL
chmod 600 $FIL
vim $FIL

getready "install helpers"
cd $HOME
mkdir -p bin etc
for FIL in gitexport pybuild; do
  cp $basedir/files/user/$FIL bin/
done
cp $basedir/files/user/pyenv.helpers etc/
source etc/pyenv.helpers
mkdir -p $VIRTUALENV_BASEDIR

getready "setup dotfiles"
mkdir -p $HOME/git
cd $HOME/git
git clone https://github.com/peterjpierce/dotfiles.git
cd $HOME
for FIL in gitconfig vimrc tmux.conf; do
  ln -s git/dotfiles/$FIL .${FIL}
  ls -l .${FIL}
done

getready "setup vim and its plugins"
$basedir/files/user/vimsetup

# manual steps
echo "Do the following to complete basic setup:"
echo "  - download, build and install python 2 and 3 to /opt/python using $HOME/bin/pybuild"
echo "  - edit .bashrc or .profile to set PATH for Python, and to source $HOME/etc/pyenv.helpers"
echo "  - verify PK auth working from remote accounts"
echo "  - update $HOME/.ssh/config within remote accounts"
